### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by edigonzales** [sogis/pdf4oereb#19]
Sind wahrscheinlich Symbole, die fehlen. Wie soll damit umgegangen werden?

```
web-service_1  | 2019-09-07 16:48:31.691 ERROR 7 --- [nio-8181-exec-4] org.apache.fop.apps.FOUserAgent          : Image not available. URI: . Reason: org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for  (See position 371:190)
web-service_1  |
web-service_1  | org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for
web-service_1  | 	at org.apache.xmlgraphics.image.loader.ImageManager.preloadImage(ImageManager.java:181) ~[xmlgraphics-commons-2.3.jar:2.3]
web-service_1  | 	at org.apache.xmlgraphics.image.loader.cache.ImageCache.needImageInfo(ImageCache.java:127) ~[xmlgraphics-commons-2.3.jar:2.3]
web-service_1  | 	at org.apache.xmlgraphics.image.loader.ImageManager.getImageInfo(ImageManager.java:123) ~[xmlgraphics-commons-2.3.jar:2.3]
web-service_1  | 	at org.apache.fop.fo.flow.ExternalGraphic.bind(ExternalGraphic.java:81) ~[fop-2.3.jar:na]
web-service_1  | 	at org.apache.fop.fo.FObj.processNode(FObj.java:126) [fop-2.3.jar:na]
web-service_1  | 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291) [fop-2.3.jar:na]
web-service_1  | 	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179) [fop-2.3.jar:na]
web-service_1  | 	at net.sf.saxon.event.ContentHandlerProxy.startContent(ContentHandlerProxy.java:385) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.event.ProxyReceiver.startContent(ProxyReceiver.java:177) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.event.SequenceNormalizer.startContent(SequenceNormalizer.java:162) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:220) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.event.ComplexContentOutputter.startContent(ComplexContentOutputter.java:662) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.event.ComplexContentOutputter.endElement(ComplexContentOutputter.java:551) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:355) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:600) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:252) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.CallTemplate.processLeavingTail(CallTemplate.java:411) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:600) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:895) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:600) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:895) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:349) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:485) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:300) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:255) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:132) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:352) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:299) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:349) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:485) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:71) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:461) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:71) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:461) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:733) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:348) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:341) [Saxon-HE-9.9.0-2.jar:na]
web-service_1  | 	at ch.so.agi.oereb.pdf4oereb.Converter.runXml2Pdf(Converter.java:262) [pdf4oereb-1.0.20.jar:na]
web-service_1  | 	at ch.so.agi.oereb.pdf4oereb.Converter.runXml2Pdf(Converter.java:286) [pdf4oereb-1.0.20.jar:na]
web-service_1  | 	at ch.ehi.oereb.webservice.OerebController.getExtractWithGeometryByEgrid(OerebController.java:334) [oereb-web-service-0.9.1-SNAPSHOT.jar:na]
web-service_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
web-service_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
web-service_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
web-service_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
web-service_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
web-service_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
web-service_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.17.jar:9.0.17]
web-service_1  | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
web-service_1  |
web-service_1  | 2019-09-07 16:48:31.695 ERROR 7 --- [nio-8181-exec-4] org.apache.fop.apps.FOUserAgent          : Image not found. URI: . (See position 371:190)
web-service_1  | 2019-09-07 16:48:31.699 ERROR 7 --- [nio-8181-exec-4] org.apache.fop.apps.FOUserAgent          : Image not found. URI: . (See position 371:190)
```

**Comment by edigonzales** [comment]
[CH368132060914_geometry_images.xml.zip](https://github.com/openoereb/pdf4oereb/files/3586874/CH368132060914_geometry_images.xml.zip)
